name: GitHub Actions Test

on: push

jobs:
  build_mvn:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn compile

  test_mvn:
    name: Test Project
    runs-on: ubuntu-latest
    needs: [build_mvn]
    steps:
      - run: tree .
      - name: Test with Maven
        run: mvn test && mvn clean test && cat target/jacoco-ut/index.html

  deploy_mvn:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: [test_mvn]
    steps:
      - run: cd target/classes/ && echo '2*x' > testfile.txt && java org.example.App < testfile.txt