name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job will be run first."

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "This job will run after build_a and build_b have finished"

  deploy:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - run: echo "This job will run after test_ab is complete"