name: GitHub Actions Test

on: push

jobs:
  btd_mvn:
    name: Build, Test and Deploy Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn compile
      - name: Test with Maven
        run: mvn test && mvn clean test && cat target/jacoco-ut/index.html
      - name: Deploy with Maven
        run: cd target/classes/ && echo '2*x' > testfile.txt && java org.example.App < testfile.txt